"""add activo column to cama

Revision ID: 9bba27e475a8
Revises: a190a089a79c
Create Date: 2025-09-30 20:40:34.387675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bba27e475a8'
down_revision: Union[str, Sequence[str], None] = 'a190a089a79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('cama', sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('true')))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cama', 'activo')
    # ### end Alembic commands ###
