"""descripcion_del_cambio

Revision ID: a0212404be54
Revises: g1h2i3j4k5l6
Create Date: 2025-10-23 10:08:43.848503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0212404be54'
down_revision: Union[str, Sequence[str], None] = 'g1h2i3j4k5l6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_area_nombre', 'area', type_='unique')
    op.drop_index('ix_cama_activo', table_name='cama')
    op.drop_index('ix_cama_id_habitacion', table_name='cama')
    op.drop_constraint('uq_habitacion_hospital_numero', 'habitacion', type_='unique')
    op.drop_index('ix_solicitud_estado', table_name='solicitud')
    op.drop_index('ix_solicitud_fecha_creacion', table_name='solicitud')
    op.drop_index('ix_solicitud_id_cama', table_name='solicitud')
    op.drop_index('ix_solicitud_identificador_qr', table_name='solicitud')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_solicitud_identificador_qr', 'solicitud', ['identificador_qr'], unique=False)
    op.create_index('ix_solicitud_id_cama', 'solicitud', ['id_cama'], unique=False)
    op.create_index('ix_solicitud_fecha_creacion', 'solicitud', ['fecha_creacion'], unique=False)
    op.create_index('ix_solicitud_estado', 'solicitud', ['estado_actual'], unique=False)
    op.create_unique_constraint('uq_habitacion_hospital_numero', 'habitacion', ['id_hospital', 'numero'])
    op.create_index('ix_cama_id_habitacion', 'cama', ['id_habitacion'], unique=False)
    op.create_index('ix_cama_activo', 'cama', ['activo'], unique=False)
    op.create_unique_constraint('uq_area_nombre', 'area', ['nombre'])
    # ### end Alembic commands ###
