"""create hospital schema

Revision ID: a190a089a79c
Revises: 
Create Date: 2025-09-30 14:27:53.453320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a190a089a79c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_area')
    )
    op.create_index(op.f('ix_area_id_area'), 'area', ['id_area'], unique=False)
    op.create_table('hospital',
    sa.Column('id_hospital', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_hospital')
    )
    op.create_index(op.f('ix_hospital_id_hospital'), 'hospital', ['id_hospital'], unique=False)
    op.create_table('habitacion',
    sa.Column('id_habitacion', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('id_hospital', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_hospital'], ['hospital.id_hospital'], ),
    sa.PrimaryKeyConstraint('id_habitacion')
    )
    op.create_index(op.f('ix_habitacion_id_habitacion'), 'habitacion', ['id_habitacion'], unique=False)
    op.create_table('cama',
    sa.Column('id_cama', sa.Integer(), nullable=False),
    sa.Column('identificador_qr', sa.String(), nullable=False),
    sa.Column('id_habitacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_habitacion'], ['habitacion.id_habitacion'], ),
    sa.PrimaryKeyConstraint('id_cama'),
    sa.UniqueConstraint('identificador_qr')
    )
    op.create_index(op.f('ix_cama_id_cama'), 'cama', ['id_cama'], unique=False)
    op.create_table('solicitud',
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('id_cama', sa.Integer(), nullable=False),
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('estado_actual', sa.Enum('ABIERTO', 'EN_PROCESO', 'RESUELTO', 'CANCELADO', name='estadosolicitud'), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_en_proceso', sa.DateTime(), nullable=True),
    sa.Column('fecha_resuelta', sa.DateTime(), nullable=True),
    sa.Column('fecha_cancelada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['area.id_area'], ),
    sa.ForeignKeyConstraint(['id_cama'], ['cama.id_cama'], ),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_index(op.f('ix_solicitud_id_solicitud'), 'solicitud', ['id_solicitud'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitud_id_solicitud'), table_name='solicitud')
    op.drop_table('solicitud')
    op.drop_index(op.f('ix_cama_id_cama'), table_name='cama')
    op.drop_table('cama')
    op.drop_index(op.f('ix_habitacion_id_habitacion'), table_name='habitacion')
    op.drop_table('habitacion')
    op.drop_index(op.f('ix_hospital_id_hospital'), table_name='hospital')
    op.drop_table('hospital')
    op.drop_index(op.f('ix_area_id_area'), table_name='area')
    op.drop_table('area')
    # ### end Alembic commands ###
